# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- release
- oldrelease
- devel

compiler:
  - gcc-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
after_success:
  - Rscript -e 'install.packages("covr"); covr::codecov()'
