// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kdr_linesearch_cpp
List kdr_linesearch_cpp(const arma::mat& X, const arma::mat& Ky, const double& sz2, const arma::mat& B, const arma::mat& dB, const double eta, const double eps, const double tol);
RcppExport SEXP KDRcpp_kdr_linesearch_cpp(SEXP XSEXP, SEXP KySEXP, SEXP sz2SEXP, SEXP BSEXP, SEXP dBSEXP, SEXP etaSEXP, SEXP epsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ky(KySEXP);
    Rcpp::traits::input_parameter< const double& >::type sz2(sz2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dB(dBSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kdr_linesearch_cpp(X, Ky, sz2, B, dB, eta, eps, tol));
    return rcpp_result_gen;
END_RCPP
}
// kdr_trace_cpp
arma::mat kdr_trace_cpp(arma::mat& X, arma::mat& Y, const unsigned int K, const int max_loop, const double sigmax0, const double sigmay0, const double eps, const double eta, const double anl, bool verbose, const double tol);
RcppExport SEXP KDRcpp_kdr_trace_cpp(SEXP XSEXP, SEXP YSEXP, SEXP KSEXP, SEXP max_loopSEXP, SEXP sigmax0SEXP, SEXP sigmay0SEXP, SEXP epsSEXP, SEXP etaSEXP, SEXP anlSEXP, SEXP verboseSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type max_loop(max_loopSEXP);
    Rcpp::traits::input_parameter< const double >::type sigmax0(sigmax0SEXP);
    Rcpp::traits::input_parameter< const double >::type sigmay0(sigmay0SEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type anl(anlSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kdr_trace_cpp(X, Y, K, max_loop, sigmax0, sigmay0, eps, eta, anl, verbose, tol));
    return rcpp_result_gen;
END_RCPP
}
// centerMatrix
arma::mat centerMatrix(const arma::mat& X);
RcppExport SEXP KDRcpp_centerMatrix(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(centerMatrix(X));
    return rcpp_result_gen;
END_RCPP
}
// distSquared
arma::mat distSquared(arma::mat A, arma::mat B);
RcppExport SEXP KDRcpp_distSquared(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(distSquared(A, B));
    return rcpp_result_gen;
END_RCPP
}
// RBFdot
arma::mat RBFdot(const arma::mat& X, const arma::mat& Y, const double sigma);
RcppExport SEXP KDRcpp_RBFdot(SEXP XSEXP, SEXP YSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RBFdot(X, Y, sigma));
    return rcpp_result_gen;
END_RCPP
}
