# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kdr_linesearch_cpp <- function(X, Ky, sz2, B, dB, eta, eps, tol = 1e-4) {
    .Call('KDRcpp_kdr_linesearch_cpp', PACKAGE = 'KDRcpp', X, Ky, sz2, B, dB, eta, eps, tol)
}

kdr_trace_cpp <- function(X, Y, K, max_loop, sigmax0, sigmay0, eps, eta, anl, verbose = TRUE, tol = 1e-9) {
    .Call('KDRcpp_kdr_trace_cpp', PACKAGE = 'KDRcpp', X, Y, K, max_loop, sigmax0, sigmay0, eps, eta, anl, verbose, tol)
}

centerMatrix <- function(X) {
    .Call('KDRcpp_centerMatrix', PACKAGE = 'KDRcpp', X)
}

distSquared <- function(A, B) {
    .Call('KDRcpp_distSquared', PACKAGE = 'KDRcpp', A, B)
}

RBFdot <- function(X, Y, sigma) {
    .Call('KDRcpp_RBFdot', PACKAGE = 'KDRcpp', X, Y, sigma)
}

